name: CI
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRESET : ${{ secrets.PRESET }}
      SOURCE : ${{ secrets.SOURCE }}
      DEST: ${{ secrets.DEST }}
      KEY: ${{ secrets.KEY }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: install ffmpeg
        run: sudo apt-get install ffmpeg -y
      - name: Run container
        run: | 
              ffmpeg \
              -re -i "$SOURCE" -i wmk.png -filter_complex "[1][0]scale2ref=w=oh*mdar:h=ih*0.08[logo][video];[video][logo]overlay=W-w-25:35" -vcodec libx264 -preset $PRESET -maxrate 3000k -b:v 2500k \
              -bufsize 600k -pix_fmt yuv420p -g 60 -c:a aac -b:a 160k -ac 2 \
              -ar 44100 -f flv -s 1280x720 "$DEST/$KEY"
